name: Run test

on: 
  push:
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v2.1.7
        id: node_modules-cache
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: yarn install --pure-lockfile --ignore-optional --network-concurrency 1
      - name: yarn test:ci
        id: run_test
        run: |
          yarn test:ci
